name: Build Page
on:
  workflow_dispatch:
  repository_dispatch:
    types: [web-page-trigger]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Run a multi-line script
        run: |
          rm -rf ./*
          git clone -b xfsc-LandingPage https://gitlab.eclipse.org/eclipse/xfsc/xfsc-website.git page
          cd page
          yarn install
          yarn build
          cd ..
          mv -f -v ./page/build/* . 
          rm -rf ./page
          git config --global user.name 'Page build Bot' 
          git config --global user.email 'pagebuildbot@memeti.com'
          git add -A .
          git commit -a -m "Bot update from eclipse gitlab"
          git push
