name: Refresh Repo Status Table

on:
  schedule:
    - cron: '0 6 */14 * *' # Alle 2 Wochen
  workflow_dispatch: # Manuell triggern möglich

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Update README Repo Status
        run: python3 scripts/repoStatus.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: eclipse-xfsc

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🤖 Update Repo Status [ci skip]" || echo "No changes"
          git push
