name: Build Page
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Hello
        run: |
          echo "hello world"
